### ISSUE TITLE
请教下源文件中使用的tensorflow版本号

### ISSUE THREAD

**Issue by Luminphantom** [percent4/people_relation_extract#10]
运行model_train.py时，会报错：module 'tensorflow' has no attribute 'logging'，原因是我使用的tensorflow2.0+中没有logging，所以想请问下源文件中的tensorflow版本号

**Comment by OliverTwist12138** [comment]
requirements里写了tensorflow==1.13.1

**Comment by Luminphantom** [comment]
感谢，后来通过requiements里的看到了。

在2020-09-18 13:25:27，ZhihanYannotifications@github.com写道：

requirements里写了tensorflow==1.13.1
