### ISSUE TITLE
能把项目的keras、tf的版本公布下吗？

### ISSUE THREAD

**Issue by joinDonk** [percent4/people_relation_extract#2]

**Comment by joinDonk** [comment]
TensorFlow 1.14 | tensorflow-1.14 | TensorFlow 1.14.0 + Keras 2.2.5 on Python 3.6.
这个版本是可以跑通的，刚开始tf是1.4的。建议大佬能写个requirements.txt

**Comment by percent4** [comment]
tf的版本是1.13.1，Keras的版本为2.2.4。BERT中文版的数据需要单独下载。
