### ISSUE TITLE
大佬，bert优化有什么建议，预测一次要10秒

### ISSUE THREAD

**Issue by joinDonk** [percent4/people_relation_extract#3]

**Comment by percent4** [comment]
预测的耗时主要集中在BERT提取特征的时候，建议将预测写成HTTP服务，那么只有在首次加载BERT时会慢，后面就会很快，也就是将下面这一行（在model_predict.py中）先加载。
bert_model = BertVector(pooling_strategy="NONE", max_seq_len=80)

**Comment by joinDonk** [comment]
谢谢大佬
